# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-01-26 18:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20180126_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2018, 1, 26, 18, 2, 34, 158000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
